language: php

php:
  - '7.2'
  - '7.3'
  - '7.4'

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - cp .env.example .env
  - travis_retry composer self-update
  - travis_retry composer update --no-interaction --prefer-dist
  - php artisan key:generate

script:
  - vendor/bin/phpunit